inicio:
    path: /
    controller: App\Controller\UserController::index
    
login:
    path: /login
    controller: App\Controller\UserController::login
    
logout:
    path: /logout
    
map:
    path: /map
    controller: App\Controller\UserController::map
    

profile:
    path: /perfil
    controller: App\Controller\UserController::profile
    
edit_profile:
    path: /editar_perfil
    controller: App\Controller\UserController::edit_profile
    
delete_profile:
    path: /delete_perfil
    controller: App\Controller\UserController::delete_profile

register_user:
    path: /registro_usuario
    controller: App\Controller\UserController::register_user

register_book:
    path: /register_book
    controller: App\Controller\CatalogueController::register_book
    
register_magazine:
    path: /register_magazine
    controller: App\Controller\CatalogueController::register_magazine
    
buscar_ini:
    path: /buscar_ini
    controller: App\Controller\AuthorityController::buscar_ini

#manage_authority:
#    path: /autores
#    controller: App\Controller\AuthorityController::index
#   
new_author:
    path: /new_author
    controller: App\Controller\AuthorityController::new_author
 
edit_delete_author:
    path: /editar_borrar_autor
    controller: App\Controller\AuthorityController::edit_delete
  
edit_author:
    path: /editar_autor/{id}
    controller: App\Controller\AuthorityController::edit
    
delete_author:
    path: /borrar_autor/{id}
    controller: App\Controller\AuthorityController::delete

search_author:
    path: /buscar_autor
    controller: App\Controller\AuthorityController::search_author

buscar_autor:
    path: /buscar_autor/{id}
    controller: App\Controller\AuthorityController::buscar

select_buscar_autor:
    path: /select_buscar_autor/{id}
    controller: App\Controller\AuthorityController::select_buscar_autor
    
catalogue:
    path: /catalogo
    controller: App\Controller\CatalogueController::all_catalogue
    
search_catalogue:
    path: /buscar_nav
    controller: App\Controller\SearchController::simpleSearch

buscar_catalogue:
    path: /buscar_catalogue
    controller: App\Controller\CatalogueController::buscar

book_details:
    path: /detalle_libro/{id}
    controller: App\Controller\CatalogueController::book_detail
    
issue_details:
    path: /detalle_numero/{id}
    controller: App\Controller\IssueController::issue_detail
    
custom_search:
    path: /busqueda_personalizada
    controller: App\Controller\SearchController::customSearch

delete_catalogue:
    path: /delete_catalogue/{id}
    controller: App\Controller\CatalogueController::delete_catalogue
    
edit_catalogue:
    path: /edit_catalogue/{id}
    controller: App\Controller\CatalogueController::edit_catalogue
      
mantenimiento:
    path: /mantenimiento
    controller: App\Controller\UserController::mantenimiento
    

issue_maintenance:
    path: /buscar_issue
    controller: App\Controller\IssueController::buscar

display_items:
    path: /ver_items/{id}
    controller: App\Controller\ItemController::display_items
    
display_issues:
    path: /ver_numeros/{id}
    controller: App\Controller\IssueController::display_issues

item_issues:
    path: /ver_items_numero/{id}
    controller: App\Controller\ItemController::display_items_issue

new_item:
    path: /crear_item/{id}
    controller: App\Controller\ItemController::create_item
    
new_issue_item:
    path: /crear_item_issue/{id}
    controller: App\Controller\ItemController::create_item_issue
    
new_issue:
    path: /crear_issue/{id}
    controller: App\Controller\IssueController::create_issue
    
edit_item:
    path: /editar_item/{id}
    controller: App\Controller\ItemController::edit_item
    
edit_issue:
    path: /editar_issue/{id}
    controller: App\Controller\IssueController::edit_issue
    
delete_item:
    path: /eliminar_item/{id}
    controller: App\Controller\ItemController::delete_item
    
delete_item_issue:
    path: /eliminar_item_issue/{id}
    controller: App\Controller\ItemController::delete_item_issue
    
delete_issue:
    path: /eliminar_issue/{id}
    controller: App\Controller\IssueController::delete_issue