index:
    path: /
    controller: App\Controller\HomeController::index
 
manage_authority:
    path: /autores
    controller: App\Controller\AuthorityController::index
   
new_author:
    path: /new_author
    controller: App\Controller\AuthorityController::new_author
 
edit_delete_author:
    path: /editar_borrar_autor
    controller: App\Controller\AuthorityController::edit_delete
  
edit_author:
    path: /editar_autor/{id}
    controller: App\Controller\AuthorityController::edit
    
delete_author:
    path: /borrar_autor/{id}
    controller: App\Controller\AuthorityController::delete

search_author:
    path: /buscar_autor
    controller: App\Controller\AuthorityController::search_author
    
catalogue:
    path: /catalogo
    controller: App\Controller\CatalogueController::all_catalogue
    
first_catalogue:
    path: /primero
    controller: App\Controller\CatalogueController::first_catalogue

search_catalogue:
    path: /buscar_nav
    controller: App\Controller\SearchController::simpleSearch
    
advanced_search:
    path: /busqueda_avanzada
    controller: App\Controller\SearchController::advancedSearch
    
custom_search:
    path: /busqueda_personalizada
    controller: App\Controller\SearchController::customSearch

login:
    path: /login
    controller: App\Controller\UserController::login

profile:
    path: /perfil
    controller: App\Controller\UserController::profile
edit_profile:
    path: /editar_perfil
    controller: App\Controller\UserController::edit_profile
delete_profile:
    path: /delete_perfil
    controller: App\Controller\UserController::delete_profile


register_user:
    path: /registro_usuario
    controller: App\Controller\UserController::register_user
        
logout:
    path: /logout

register_book:
    path: /register_book
    controller: App\Controller\CatalogueController::register_book

register_book_autor:
    path: /register_book_autor/{id}
    controller: App\Controller\CatalogueController::register_book_autor

buscar_ini:
    path: /buscar_ini
    controller: App\Controller\AuthorityController::buscar_ini
    
buscar_autor:
    path: /buscar_autor/{id}
    controller: App\Controller\AuthorityController::buscar
    
select_buscar_autor:
    path: /select_buscar_autor/{id}
    controller: App\Controller\AuthorityController::select_buscar_autor
    
buscar_catalogue:
    path: /buscar_catalogue
    controller: App\Controller\CatalogueController::buscar

item_maintenance:
    path: /buscar_item
    controller: App\Controller\ItemController::buscar

display_items:
    path: /ver_items/{id}
    controller: App\Controller\ItemController::display_items

new_item:
    path: /crear_item/{id}
    controller: App\Controller\ItemController::create_item
    
edit_item:
    path: /editar_item/{id}
    controller: App\Controller\ItemController::edit_item
#    
delete_item:
    path: /eliminar_item/{id}
    controller: App\Controller\ItemController::delete_item
#    
#asign_authors:
#    path: /asign_authors/{id}
#    controller: App\Controller\AuthorityController::asign_authors