#*********************USER********************************#
inicio:
    path: /
    controller: App\Controller\UserController::index
    
login:
    path: /login
    controller: App\Controller\UserController::login
    
logout:
    path: /logout
    
map:
    path: /map
    controller: App\Controller\UserController::map

mantenimiento:
    path: /mantenimiento
    controller: App\Controller\UserController::mantenimiento

profile:
    path: /profile
    controller: App\Controller\UserController::profile
    
edit_profile:
    path: /edit_profile
    controller: App\Controller\UserController::edit_profile
    
delete_profile:
    path: /delete_perfil
    controller: App\Controller\UserController::delete_profile

register_user:
    path: /register_user
    controller: App\Controller\UserController::register_user
    
search_generic:
    path: /search_generic
    controller: App\Controller\UserController::search_generic


#*********************CATALOGUE********************************#

register_book:
    path: /register_book
    controller: App\Controller\CatalogueController::register_book
    
register_magazine:
    path: /register_magazine
    controller: App\Controller\CatalogueController::register_magazine

delete_catalogue:
    path: /delete_catalogue/{id}
    controller: App\Controller\CatalogueController::delete_catalogue
    
edit_catalogue:
    path: /edit_catalogue/{id}
    controller: App\Controller\CatalogueController::edit_catalogue
      
search_catalogue:
    path: /search_catalogue
    controller: App\Controller\CatalogueController::search_catalogue
      
search_catalogue_ini:
    path: /search_catalogue_ini
    controller: App\Controller\CatalogueController::search_catalogue_ini

book_details:
    path: /book_details/{id}
    controller: App\Controller\CatalogueController::book_detail

#manage_authority:
#    path: /autores
#    controller: App\Controller\AuthorityController::index
#   
#*********************AUTHORITY********************************#
unassign_autority:
    path: /unassign_author/{id_catalogue}-{id_authority}
    controller: App\Controller\AuthorityController::unassign_author
    
register_author:
    path: /register_author
    controller: App\Controller\AuthorityController::register_author
 
#edit_delete_author:
#    path: /edit_delete_author
#    controller: App\Controller\AuthorityController::edit_delete
  
edit_author:
    path: /edit_author/{id}
    controller: App\Controller\AuthorityController::edit
    
delete_author:
    path: /delete_author/{id}
    controller: App\Controller\AuthorityController::delete_author

search_authority_ini:
    path: /search_authority_ini
    controller: App\Controller\AuthorityController::search_authority_ini

search_author:
    path: /search_author
    controller: App\Controller\AuthorityController::search_author
    
detail_author:
    path: /detalle_author/{id}
    controller: App\Controller\AuthorityController::detail_author
    
buscar_autor_ini:
    path: /buscar_autor_ini/{id}
    controller: App\Controller\AuthorityController::buscar_autor_ini
    
buscar_autor:
    path: /buscar_autor
    controller: App\Controller\AuthorityController::buscar

asign_autor:
    path: /asign_autor/{id}
    controller: App\Controller\AuthorityController::asign_autor
    
#*********************SEARCH********************************#

#search_catalogue:
#    path: /buscar_nav
#    controller: App\Controller\SearchController::simpleSearch
    
custom_search:
    path: /busqueda_personalizada
    controller: App\Controller\SearchController::customSearch


#*********************ISSUE********************************#

search_issue_ini:
    path: /search_issue_ini
    controller: App\Controller\IssueController::search_issue_ini

detail_issue:
    path: /detalle_numero/{id}-{id_catalogue}
    controller: App\Controller\IssueController::detail_issue

search_issue:
    path: /search_issue
    controller: App\Controller\IssueController::search_issue
    
search_issues:
    path: /search_issues/{id}
    controller: App\Controller\IssueController::search_issues
    
new_issue:
    path: /new_issue/{id}
    controller: App\Controller\IssueController::create_issue
    
edit_issue:
    path: /edit_issue/{id}
    controller: App\Controller\IssueController::edit_issue
    
delete_issue:
    path: /delete_issue/{id}
    controller: App\Controller\IssueController::delete_issue
    
issue_ini:
    path: /issue_detail/{id}
    controller: App\Controller\IssueController::issue_ini
    
    
#************************ITEM********************************#

search_items:
    path: /search_items/{id}
    controller: App\Controller\ItemController::search_items

item_issues:
    path: /item_issues/{id}
    controller: App\Controller\ItemController::display_items_issue

register_item:
    path: /register_item/{id}
    controller: App\Controller\ItemController::register_item
    
register_issue_item:
    path: /register_issue_item/{id}
    controller: App\Controller\ItemController::register_issue_item
    
edit_item:
    path: /editar_item/{id}
    controller: App\Controller\ItemController::edit_item
    
delete_item:
    path: /delete_item/{id}
    controller: App\Controller\ItemController::delete_item
    
delete_item_issue:
    path: /eliminar_item_issue/{id}
    controller: App\Controller\ItemController::delete_item_issue