index:
    path: /
    controller: App\Controller\HomeController::index
 
    
catalogue:
    path: /catalogo
    controller: App\Controller\CatalogueController::all_catalogue
    
first_catalogue:
    path: /primero
    controller: App\Controller\CatalogueController::first_catalogue


login:
    path: /login
    controller: App\Controller\UserController::login
    
    
register_user:
    path: /registro_usuario
    controller: App\Controller\UserController::register_user
        
logout:
    path: /logout
   
#    Route::get('/', 'CategoriasController@index');
#//Route::resource('secciones', 'CategoriasController');
#
#Route::resource('categorias', 'CategoriasController');
#Route::get('/buscar','ProductosController@buscar');
#Route::resource('categorias.productos', 'ProductosController');
#
#Route::get('/home', 'HomeController@index')->name('home');
#Route::get('/darBaja','HomeController@darBaja');
#Route::get('/perfil', 'HomeController@perfil');
#Route::get('/editar','HomeController@editar');
#Route::get('/mapa', 'SoapController@show');
#Route::get('/register/verify/{code}', 'HomeController@verify');
#Route::get('/alfabetico','ProductosController@alfabetico');
#Route::get('/mayor_precio','ProductosController@mayor');
#Route::get('/menor_precio','ProductosController@menor');
#Route::get('/cat_alfabetico','CategoriasController@alfabetico');
#Route::get('/cat_mayor','CategoriasController@mayor');
#Route::get('/cat_menor','CategoriasController@menor');