<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEBECkwx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEBECkwx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEBECkwx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEBECkwx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEBECkwx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EBECkwx',
    'container.build_id' => '6741268d',
    'container.build_time' => 1555692742,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEBECkwx');
