<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3ixRhqC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3ixRhqC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3ixRhqC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3ixRhqC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3ixRhqC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3ixRhqC',
    'container.build_id' => '2de7a046',
    'container.build_time' => 1557523814,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3ixRhqC');
